import { Document, Packer, Paragraph, TextRun } from 'docx'
import { saveAs } from 'file-saver'

export async function exportDocFree(text: string) {
  if (!text) return

  const paragraphs = text
    .split('\n\n')
    .filter(Boolean)
    .map(line =>
      new Paragraph({
        children: [new TextRun(line)],
        spacing: { after: 200 },
      })
    )

  // Add subtle watermark
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by CleanDoc Free',
          italics: true,
          color: '808080',
          size: 18,
        }),
      ],
      spacing: { before: 400 },
    })
  )

  const doc = new Document({ sections: [{ children: paragraphs }] })
  const blob = await Packer.toBlob(doc)
  saveAs(blob, 'CleanDoc_Free.docx')
}