import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from 'docx';
import { saveAs } from 'file-saver';

interface ExportOptions {
  showGeneratedBy?: boolean; // Optional, default false
  username?: string;
}

export async function exportDocPro(
  cleanedText: string,
  options: ExportOptions = {}
) {
  if (!cleanedText) return;

  const { showGeneratedBy = false, username } = options;

  const lines = cleanedText.split(/\n+/).map((l) => l.trim()).filter(Boolean);

  const paragraphs: Paragraph[] = [];
  let currentBulletLevel = 0;

  for (let line of lines) {
    // 1️⃣ Bullet detection
    const bulletMatch = line.match(/^(\s*)([-*])\s+(.*)$/);
    if (bulletMatch) {
      const [, spaces, , content] = bulletMatch;
      const level = Math.floor(spaces.length / 2); // 2 spaces per indent
      paragraphs.push(
        new Paragraph({
          text: content,
          bullet: { level },
          spacing: { after: 150 },
        })
      );
      continue;
    }

    // 2️⃣ Header detection
    // Lines ending with ":" or all uppercase, or "Key Highlights", "Next Steps", etc.
    const headerKeywords = ['Key Highlights', 'Next Steps', 'Note', 'Urgent Attention'];
    const isHeader =
      line.endsWith(':') ||
      line === line.toUpperCase() ||
      headerKeywords.some((k) => line.startsWith(k));

    const parts = line.split('**'); // bold highlights
    const runs = parts.map((part, i) =>
      new TextRun({
        text: part.trim(),
        bold: i % 2 !== 0,
      })
    );

    if (isHeader) {
      paragraphs.push(
        new Paragraph({
          children: runs,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 200 },
          alignment: AlignmentType.LEFT,
        })
      );
      continue;
    }

    // 3️⃣ Inline highlights (keywords, numbers, emails)
    const enhancedRuns: TextRun[] = [];
    const keywords = [
      'Name',
      'Date',
      'Email',
      'Phone',
      'Address',
      'Amount',
      'Price',
      'Deadline',
      'Signature',
      'Department',
      'Title',
      'Reference',
      'Subject',
      'Note',
      'Terms',
      'Agreement',
    ];

    let remaining = line;
    const regex = new RegExp(
      `(${keywords.join('|')}|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}|₦\\s*\\d+(?:\\.\\d{1,2})?|\\$\\s*\\d+(?:\\.\\d{1,2})?)`,
      'gi'
    );

    let match;
    while ((match = regex.exec(remaining))) {
      const before = remaining.slice(0, match.index);
      if (before) enhancedRuns.push(new TextRun({ text: before }));

      enhancedRuns.push(
        new TextRun({ text: match[0], bold: true, color: '000000' })
      );
      remaining = remaining.slice(match.index + match[0].length);
      regex.lastIndex = 0;
    }
    if (remaining) enhancedRuns.push(new TextRun({ text: remaining }));

    paragraphs.push(
      new Paragraph({
        children: enhancedRuns.length ? enhancedRuns : runs,
        spacing: { after: 150 },
      })
    );
  }

  // 4️⃣ Optional closing note (not a watermark)
  if (showGeneratedBy) {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by CleanDoc Pro${username ? ` — ${username}` : ''}`,
            italics: true,
            color: '555555',
            size: 18,
          }),
        ],
        spacing: { before: 400 },
        alignment: AlignmentType.RIGHT,
      })
    );
  }

  const doc = new Document({
    sections: [{ children: paragraphs }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, 'CleanDoc_Pro.docx');
}