import { Document, Packer, Paragraph, TextRun } from 'docx'
import { saveAs } from 'file-saver'

export async function exportDocFree(text: string) {
  if (!text) return

  // Split text into paragraphs
  const paragraphs = text
    .split('\n\n')
    .filter(Boolean)
    .map(line =>
      new Paragraph({
        children: [new TextRun(line)],
        spacing: { after: 200 },
      })
    )

  // Add subtle footer
  paragraphs.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by CleanDoc Free',
          italics: true,
          color: '808080',
          size: 18,
        }),
      ],
      spacing: { before: 400 },
    })
  )

  // ✨ Add faint diagonal watermark text
  const watermarkParagraph = new Paragraph({
    children: [
      new TextRun({
        text: 'CLEANDOC FREE VERSION',
        bold: true,
        color: 'D3D3D3', // light gray
        size: 72, // large, but faint
      }),
    ],
    alignment: 'center',
    spacing: { after: 200 },
  })

  const doc = new Document({
    sections: [
      {
        headers: {
          default: watermarkParagraph, // Watermark in header area
        },
        children: paragraphs,
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, 'CleanDoc_Free.docx')
}