import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableCell,
  TableRow,
  WidthType,
} from 'docx';
import { saveAs } from 'file-saver';

interface ExportOptions {
  showGeneratedBy?: boolean;
  username?: string;
}

const HEADER_KEYWORDS = [
  'Title','Abstract','Executive Summary','Table of Contents','List of Figures','List of Tables','Acknowledgements','Dedication',
  'Introduction','Background','Problem Statement','Scope','Objective','Purpose','Hypothesis','Review of Literature','Theoretical Framework',
  'Methodology','Methods','Procedure','Materials','Equipment','Data','Results','Findings','Analysis','Discussion','Limitations',
  'Conclusion','Summary of Findings','Recommendations','Future Work','Glossary','Index','References','Bibliography','Works Cited',
  'Appendix','Appendices','Chapter','Section','Definition','Context','Evaluation','Implementation','Testing','Schedule','Timeline',
  'Budget','Cost Analysis','Next Steps','Assumptions','Key Terms'
];

export async function exportDocProNextGen(
  cleanedText: string,
  options: ExportOptions = {}
) {
  if (!cleanedText) return;

  const { showGeneratedBy = false, username } = options;

  const lines = cleanedText.split(/\n+/).map(l => l.trim()).filter(Boolean);
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    // 1️⃣ Bullet / numbered list detection
    const bulletMatch = line.match(/^(\s*)([-*]|\d+\.)\s+(.*)$/);
    if (bulletMatch) {
      const [_, spaces, marker, content] = bulletMatch;
      const level = Math.floor(spaces.length / 2);
      const isNumbered = /\d+\./.test(marker);

      paragraphs.push(
        new Paragraph({
          text: content,
          bullet: isNumbered ? undefined : { level },
          numbering: isNumbered ? { reference: 'numbered-list', level } : undefined,
          spacing: { after: 120 },
        })
      );
      continue;
    }

    // 2️⃣ Header detection (standalone or ending with colon)
    const isStandaloneHeader = HEADER_KEYWORDS.some(k => line === k || line.startsWith(k + ':'));
    if (isStandaloneHeader) {
      let headingLevel = HeadingLevel.HEADING_1;

      // Chapter or Section keywords → H1, others → H2
      if (/Chapter|Section/i.test(line)) headingLevel = HeadingLevel.HEADING_1;
      else headingLevel = HeadingLevel.HEADING_2;

      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text: line, bold: true })],
          heading: headingLevel,
          spacing: { before: 300, after: 200 },
          alignment: AlignmentType.LEFT,
        })
      );
      continue;
    }

    // 3️⃣ Key Highlights / Next Steps block styling
    if (/^(Key Highlights|Next Steps|Note|Urgent Attention)/i.test(line)) {
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text: line, bold: true })],
          spacing: { before: 200, after: 200 },
          shading: { fill: 'FFFFCC' },
        })
      );
      continue;
    }

    // 4️⃣ Normal paragraphs with inline highlights
    const enhancedRuns: TextRun[] = [];
    const keywords = [
      'Name', 'Date', 'Email', 'Phone', 'Address', 'Amount', 'Price', 'Deadline',
      'Signature', 'Department', 'Title', 'Reference', 'Subject', 'Note', 'Terms', 'Agreement'
    ];

    let remaining = line;
    const regex = new RegExp(
      `(${keywords.join('|')}|[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}|₦\\s*\\d+(?:\\.\\d{1,2})?|\\$\\s*\\d+(?:\\.\\d{1,2})?)`,
      'gi'
    );

    let match;
    while ((match = regex.exec(remaining))) {
      const before = remaining.slice(0, match.index);
      if (before) enhancedRuns.push(new TextRun({ text: before }));
      enhancedRuns.push(new TextRun({ text: match[0], bold: true, color: '000000' }));
      remaining = remaining.slice(match.index + match[0].length);
      regex.lastIndex = 0;
    }
    if (remaining) enhancedRuns.push(new TextRun({ text: remaining }));

    paragraphs.push(
      new Paragraph({
        children: enhancedRuns.length ? enhancedRuns : [new TextRun({ text: line })],
        spacing: { after: 150 },
      })
    );
  }

  // 5️⃣ Optional closing note
  if (showGeneratedBy) {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by CleanDoc Pro${username ? ` — ${username}` : ''}`,
            italics: true,
            color: '555555',
            size: 18,
          }),
        ],
        spacing: { before: 400 },
        alignment: AlignmentType.RIGHT,
      })
    );
  }

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: 'numbered-list',
          levels: Array.from({ length: 9 }, (_, i) => ({
            level: i,
            format: 'decimal',
            text: '%1.',
            alignment: AlignmentType.START,
          })),
        },
      ],
    },
    sections: [{ children: paragraphs }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, 'CleanDoc_Pro_NextGen.docx');
}